---
- name: restart flower
  supervisorctl:
    state: restarted
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    name: "{{ FLOWER_USER }}"
  become: true
  become_user: "{{ supervisor_service_user }}"
