- name: Deploy the Course Authoring MFE
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'course-authoring'
    COURSE_AUTHORING_ENABLED: True
    COURSE_AUTHORING_SANDBOX_BUILD: False
  roles:
    - role: course_authoring
      MFE_NAME: course-authoring
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELICE_INFRASTRUCTURE