- name: Deploy the Library Authoring MFE
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'library-authoring'
    LIBRARY_AUTHORING_ENABLED: True
    LIBRARY_AUTHORING_SANDBOX_BUILD: False
  roles:
    - role: library_authoring
      MFE_NAME: library-authoring
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELICE_INFRASTRUCTURE