- name: Deploy profile Frontend
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'profile'
    PROFILE_MFE_ENABLED: True
    PROFILE_MFE_SANDBOX_BUILD: False
  roles:
    - role: mfe
      MFE_NAME: profile
      MFE_VERSION: '{{ PROFILE_MFE_VERSION }}'
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
